import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.WindowEvent;
import java.util.Random;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author msash9
 */
public class ProgressBar extends javax.swing.JFrame 
{

	private static int counterParagraph = 0;
	private int counter =0;
	private int valueProgressBar =0;
   
    
  
    public ProgressBar(int counter) 
    {    
    	this.setLocation(400,300);
    	this.setTitle("Screening...");
        initComponents();        
        counterParagraph = counter;
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                   

                                         

    public void jButtonMouseClicked(java.awt.event.MouseEvent evt)   
    {                                     
    	
    }  
    
    public void run ( int counter)
    {
    	
    		// Perform all of our bogus tasks
 		 			
 			// Do some sort of simulated task
 			
 			DoBogusTask(counter);
 			

 			// Update the progress indicator and label
 			jTextArea2.setFont(new Font("Arial", Font.PLAIN, 16));
 			jTextArea2.setText( "Loading..." + "\n"+"\n"+ "Record " + counter + " of "+counterParagraph+" finished!");
 			jTextArea2.setVisible(true);
 			Rectangle labelRect = jTextArea2.getBounds();
 			labelRect.x = 0;
 			labelRect.y = 0; 			
 			jTextArea2.paintImmediately(labelRect);		
 			
 			
 			jProgressBar2.setMaximum(counterParagraph);
 			jProgressBar2.setValue(counter);
 			jProgressBar2.setVisible(true);
 			
 			
 			Rectangle progressRect = jProgressBar2.getBounds();
 			progressRect.x = 0;
 			progressRect.y = 0;
 			jProgressBar2.paintImmediately( progressRect );
 			 			
 			
 			counter=counter+1;
 			
 			if(counter == counterParagraph+1||counter==1)
 			{
 				
 				try
 				{ 	
 					jTextArea2.setFont(new Font("Arial",Font.BOLD,14));
 					jTextArea2.setText("\n"+"\n"+"\n"+"\n"+"\n"+"\n"+"RUN completed! Files have been created -"+"\n"+"Please close the programm. Process is finished");
 					Rectangle labelRect2 = jTextArea2.getBounds();
 					labelRect2.x = 0;
 					labelRect2.y = 60;
 					jTextArea2.paintImmediately( labelRect2 );
 						
 					Thread.sleep(3000);
 					this.dispose(); 					
 					
 				}
 				catch(InterruptedException e)
 				{

 				} 				
 			} 
    }
    
    
    
    public void DoBogusTask( int i )
	{
		Random random = new Random( i );

		// Waste some time
		for( int iValue = 0; iValue < random.nextFloat() * 100; iValue++ )
		{
			
		}
	}
    
    protected void processWindowEvent(WindowEvent e)
	{

		super.processWindowEvent(e);
		if(e.getID()==WindowEvent.WINDOW_CLOSING)
		{
			this.dispose();
		}

	}
	

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) 
    {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new ProgressBar(counterParagraph).setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    
    // End of variables declaration                   
}
